---
title: "Time Series Model"
author: "Zixiao Wang"
date: "2019/4/28"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(forecast)
library(plotly)
library(ggfortify)
library(tseries)
library(gridExtra)
library(readr)
library(MASS)
```

## Load the Data

```{r}
gtrain_new <- read_csv("../data/gtrain_ts.csv")
```

## Compute Daily Revenue

```{r}
date_wise <- gtrain_new  %>%
group_by(date)  %>%
summarise(daily_transactionRevenue = sum(transactionRevenue, na.rm =TRUE))
```

## Model Preparation

```{r}
acf(date_wise$daily_transactionRevenue)
pacf(date_wise$daily_transactionRevenue)
```

Based on this plots, it could be observed that there is a seasonal pattern at lag 7, which makes sense since it could be a weekly pattern.

```{r}
# Convert data to time series based on observation
TRDts <- ts(date_wise$daily_transactionRevenue, frequency = 7)
plot.ts(date_wise$daily_transactionRevenue, main = "Daily Transaction Revenue")
```

```{r}
# Note that the third observation is 0, which could not be used in this test. Thus, we drop it for the test.
ntD=1:length(TRDts)
bcTransD = boxcox(TRDts[-3]~ntD[-3])
lambdaD = bcTransD$x[which(bcTransD$y == max(bcTransD$y))]
lambdaD
```

```{r}
dataTrans=(TRDts)^(0.3)
ts.plot(dataTrans)
var(dataTrans)

# Reference: https://www.ime.usp.br/~abe/lista/pdfQWaCMboK68.pdf
```

## Model Selection

```{r}
# Select model based on AIC
auto.arima(dataTrans)
```

```{r}
fit1 <- arima(dataTrans, order=c(1,0,1), seasonal=list(order=c(2,1,0), period=7))
fit1
```

```{r}
# Check assumptions for residuals
# Test for independence of residuals
Box.test(residuals(fit1), type="Ljung")

plot(residuals(fit1))

# Histogram
hist(residuals(fit1),main = "Histogram")
# q-q plot
qqnorm(residuals(fit1)) 
qqline(residuals(fit1),col ="blue")
```

## Cross Validation

```{r}
# Cross validation test error RMSE
# We compare the RMSE obtained via time series cross-validation with the residual RMSE
data_new <- c(dataTrans)
fit_new <- function(x, h){
  forecast(arima(x, order=c(1,0,1), seasonal=list(order=c(2,1,0), period=7)), h=h)
}
e <- tsCV(data_new, fit_new, h=1)

# Cross Validation Error (Predicted Test Error)
sqrt(mean(e^2, na.rm=TRUE))

# Training Error
sqrt(mean(residuals(arima(data_new, order=c(1,0,1), seasonal=list(order=c(2,1,0), period=7)), h=1)^2, na.rm=TRUE))
```

## Prediction

```{r}
# First attempt
fit_new = arima(ts(dataTrans), order=c(1,0,1), seasonal=list(order=c(2,1,0), period=7))
fcast_new <- forecast(fit_new,h=60)
plot(fcast_new, main=" ")

#Improvement of Forecasting
dataNew <- NULL
dataUpper <- matrix(nrow = 60,ncol = 2)
dataUpper[,1] <- c(367:426)
dataLower <- matrix(nrow = 60,ncol = 2)
dataLower[,1] <- c(367:426)
dataNew <- as.numeric(dataTrans) 
length(dataNew) <- 426

for(i in 1:60){
  fit_new = arima(ts(dataNew[(247+(i-1)):(366+(i-1))], frequency = 7), order=c(1,0,1), seasonal=list(order=c(2,1,0), period=7))
  fcast_new <- forecast(fit_new, h=1)
  dataNew[366+i] <- fcast_new$mean
  dataUpper[i,2] <- fcast_new$upper[2]
  dataLower[i,2] <- fcast_new$lower[2]
}

dataCI <- matrix(NA, nrow = 426, ncol = 4)
dataCI[,1] <- c(1:426)
dataCI[,2] <- dataNew
dataCI[367:426,3] <- dataUpper[,2]
dataCI[367:426,4] <- dataLower[,2]
colnames(dataCI) <- c("date", "Reveune", "upper", "lower")

ts.plot(dataNew, xlab = "", ylab = "", main = "Improved Forecasting")
lines(dataUpper, col="blue", lty = 3)
lines(dataLower, col="blue", lty = 3)

# ggplot(data.frame(dataCI), aes(x = date, y = Reveune)) + 
#   geom_line(color = "blue", size = 0.05) +
#   geom_ribbon(data=dataCI,aes(ymin=lower,ymax=upper),alpha=0.3) +
#   theme_minimal() +
#   ylim(low=0,high=20)
```

To get the prediction of revenue, we need to transform data into the original form.

```{r}
#(fcast_new$mean)^(10/3)
(dataNew[367:426])^(10/3)
```
